name: Deploy to GoDaddy Shared Hosting DevAtmos Node js test project

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST || env.SSH_HOST }}
          port: ${{ secrets.SSH_PORT || env.SSH_PORT }}
          username: ${{ secrets.SSH_USER || env.SSH_USER }}
          password: ${{ secrets.SSH_PASS || env.SSH_PASS }}
          script: |
            mkdir -p ~/nodeapps/airport
            cd ~/nodeapps/airport
            if [ ! -d ".git" ]; then
              git clone https://github.com/dev-atmos/godaddy-node-sample.git .
            else
              git pull origin main
            fi

            # Ensure NVM is loaded
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            # Use Node.js 18
            nvm install 18
            nvm use 18

            npm install --production

            # Install PM2 if not installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Restart or start the app
            pm2 restart airport || pm2 start server.js --name airport
