name: Deploy to GoDaddy Shared Hosting DevAtmos Node js test project

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ 184.168.109.78 }}
          port: ${{22}}
          username: ${{ b6mo64ug6v9q }}
          password: ${{ Tqdf6#Y2#8J4 }}
          script: |
            mkdir -p ~/nodeapps/airport
            cd ~/nodeapps/airport
            if [ ! -d ".git" ]; then
              git clone https://github.com/dev-atmos/godaddy-node-sample.git .
            else
              git pull origin main
            fi
            source ~/.bashrc
            nvm use 18
            npm install --production
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            pm2 restart airport || pm2 start server.js --name airport
