name: Deploy to GoDaddy Shared Hosting with nvm

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH (nvm friendly)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            nvm use 18

            mkdir -p ~/airport
            cd ~/airport

            if [ ! -d .git ]; then
              git clone https://${{ secrets.GH_PAT }}@github.com/Dev-Atmos/godaddy-node-sample.git .
            else
              git pull https://${{ secrets.GH_PAT }}@github.com/Dev-Atmos/godaddy-node-sample.git main
            fi

            npm install
            npx pm2 restart airport || npx pm2 start server.js --name airport
